chrX coding
genetics-of-dna-methylation-consortium/godmc_phase2 pull request #58
Opened 2024-10-28 11:52 UTC by epzjlm

2024-12-03 20:23 UTC, ejh243 requested changes
I am not sure you mean to entirely delete 02a, won't this scupper the rest of the pipeline? If you do mean it, surely we would also want to update the numbering on 02b etc?

2024-12-03 20:23 UTC, ejh243 commented on 02a-snp_data.sh
Do you mean to completely delete this file?

2024-12-03 21:53 UTC, epzjlm commented on 02a-snp_data.sh
no it shouldn't be deleted. It should be the same as the file in the main branch. I think I now added the latest version.

2024-12-19 10:05 UTC, ejh243 commented
Waiting for @drsora to confirm that the fix on this branch works before approving and merging.

2024-12-20 10:59 UTC, drsora commented
I managed to run everything through but check upload tells me 4a didn't run correctly. I reran it and get this output:

```
Number of individuals 887 
  family individual  paternal  maternal  sex  label
0      5          5         0         0    2     -9
1      6          6         0         0    2     -9
2     13         13         0         0    2     -9
3     14         14         0         0    2     -9
4     20         20         0         0    2     -9
There should be 2 files in probes folder, you have 3!
Converted number of variants 7680276
   CHR            ID  distance      bp      allele1     allele2
0    1  1:752566_A_G         0  752566   9088027334  8320025024
1    1  1:752721_A_G         0  752721   8320025024  9088027334
2    1  1:753405_A_C         0  753405   8576025794  8320025024
3    1  1:753541_A_G         0  753541   8320025024  9088027334
4    1  1:754063_G_T         0  754063  10752032341  9088027334
5    1  1:754105_C_T         0  754105  10752032341  8576025794
6    1  1:754182_A_G         0  754182   8320025024  9088027334
7    1  1:754192_A_G         0  754192   8320025024  9088027334
8    1  1:754334_C_T         0  754334  10752032341  8576025794
9    1  1:754503_A_G         0  754503   9088027334  8320025024
Number of variants in genotype folder 7680276
[[2 2 2 ... 2 2 2]
 [2 2 2 ... 2 2 2]
 [1 1 1 ... 1 2 1]
 ...
 [2 2 2 ... 2 2 1]
 [1 2 2 ... 1 2 2]
 [2 2 2 ... 2 2 2]]
Time to convert all data: 2356.93731904 sec
experiment finished in 2357.08545899 s
```

I checked case_converting/probes and there's only 2 files there.

2024-12-20 12:36 UTC, drsora commented
Not sure what happened with my previous comment but I 4 ran fully on this branch but check_upload says 4a didn't complete successfully. Not sure why, I reran it (again) and it doesn't say anything about an error. I'm attaching the log.
This was with Luric, I can try if it with YFS. 
[log.txt](https://github.com/user-attachments/files/18210767/log.txt)

2025-01-25 21:49 UTC, SiyiSEA approved these changes

2025-01-27 09:29 UTC, merged